{
 "title": "Cluster Overview by Client",
 "description": "Endpoint Selectable Volumes and Response Times",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from client_verb_stats  group by cluster"
   },
   {
    "name": "client",
    "query": "select client from client_verb_stats where cluster = $cluster group by client"
   },
   { "name": "min_GET", "query": "SELECT 0,10,100,1000" },
   { "name": "min_POST", "query": "SELECT 0,10,100,1000" },
   { "name": "min_PUT", "query": "SELECT 0,10,100,1000" },
   { "name": "min_DELETE", "query": "select 0,10,100,1000" }
  ]
 },
 "panels": [
  {
   "title": "GET volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and verb='GET' and cluster=$cluster group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(tqcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='GET' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_POST as int) and verb='POST' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(tqcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='POST' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "DELETE volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_DELETE as int) and verb='DELETE' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(tqcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='DELETE' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET travg (Cloudant db processing)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and verb='GET' and cluster=$cluster group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='GET' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_POST as int) and verb='POST' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='POST' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "DELETE  travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_DELETE as int) and verb='DELETE' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='DELETE' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET (tt-tr)avg (All except cloudant db)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and verb='GET' and cluster=$cluster group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='GET' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_POST as int) and verb='POST' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='POST' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_PUT as int) and verb='PUT' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='PUT' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_DELETE as int) and verb='DELETE' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='DELETE' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and verb='GET' and cluster=$cluster group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value \nfrom client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='GET' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric\n"
    }
   ]
  },
  {
   "title": "POST fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_POST as int) and verb='POST' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value \nfrom client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='POST' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_PUT as int) and verb='PUT' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value \nfrom client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='PUT' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.client as metric,b.mtime_epoch as time from \n(select client from client_verb_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_DELETE as int) and verb='DELETE' and cluster=$cluster  group by client) a , \n(select mtime_epoch from client_verb_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.client in ($client))c \nLEFT OUTER JOIN \n(select client as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value \nfrom client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch) and verb='DELETE' and client in ($client) and cluster=$cluster\ngroup by client,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  }
 ]
}