{
 "title": "Compaction Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "select chr(39)||cluster||chr(39) from db_stats group by cluster"
   },
   {
    "name": "project",
    "query": "SELECT CASE WHEN substring(database,0,position('_' in database)) = '' THEN 'others' ELSE substring(database,0,position('_' in database)) END as project from db_stats where cluster=$cluster and database is not null group by project order by project"
   },
   {
    "name": "database",
    "query": "select database from db_stats where cluster=$cluster and database in (select database from db_stats where doc_count >= $min_db_docs and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster)) and CASE WHEN substring(database,0,position('_' in database)) = '' THEN 'others' ELSE substring(database,0,position('_' in database)) END in ($project) group by database order by database"
   },
   {
    "name": "min_db_docs",
    "query": "select 0,10,100,1000,10000,100000"
   },
   {
    "name": "host",
    "label": "dbnode",
    "query": "select host from ioq_stats where cluster = $cluster group by host"
   },
   {
    "name": "dbchannel",
    "query": "select channel from smoosh_stats where cluster=$cluster and channel like '%dbs' group by channel"
   },
   {
    "name": "viewchannel",
    "query": "select channel from smoosh_stats where cluster=$cluster and channel like '%views' group by channel"
   }
  ]
 },
 "panels": [
  {
   "title": "dbcompact%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  100*data_size/disk_size as value\nFROM\n  db_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster = $cluster and database in ($database)\n  order by time,metric"
    }
   ]
  },
  {
   "title": "db Jobs Waiting (at sample point/min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  channel as metric,\n  mtime_epoch as time,\n  sum(waiting) as value\nFROM\n  smoosh_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch) \n  and cluster = $cluster \n  and host in ($host)\n  and channel in ($dbchannel)\n  group by channel,mtime_epoch\n  order by time, channel\n"
    }
   ]
  },
  {
   "title": "viewcompact% (db totals)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  CASE WHEN sum(disk_size) is null or sum(disk_size) = 0 then 0\n  else 100*sum(active_size)/sum(disk_size) end as value\nFROM\n  view_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and database in ($database)\n  group by database,mtime_epoch\n  order by time,metric"
    }
   ]
  },
  {
   "title": "view  Jobs Waiting (at sample point/min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  channel as metric,\n  mtime_epoch as time,\n  sum(waiting) as value\nFROM\n  smoosh_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch) \n  and cluster = $cluster \n  and host in ($host)\n  and channel in ($viewchannel)\n  group by  channel,mtime_epoch\n  order by time, channel\n"
    }
   ]
  },
  {
   "title": "db size (MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  cast (disk_size/1048576 as decimal(8,2)) as value\nFROM\n  db_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and database in ($database)\n  order by time,metric\n"
    }
   ]
  },
  {
   "title": "db  Jobs Active/Starting (at sample point/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  channel as metric,\n  mtime_epoch as time,\n  sum(active)+sum(starting) as value\nFROM\n  smoosh_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch) \n  and cluster = $cluster\n  and host in ($host)\n  and channel in ($dbchannel) \n  group by channel,mtime_epoch\n  order by time, channel\n"
    }
   ]
  },
  {
   "title": "view size (db total MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  cast (sum(data_size)/1048576 as decimal(8,2)) as value\nFROM\n  view_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and database in ($database)\n  group by metric,time\n  order by time,metric\n"
    }
   ]
  },
  {
   "title": "view Jobs Active/Starting (at sample point/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   channel as metric,\n  mtime_epoch as time,\n  sum(active)+sum(starting) as value\nFROM\n  smoosh_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch) \n  and cluster = $cluster\n  and host in ($host)\n  and channel in ($viewchannel) \n  group by  channel,mtime_epoch\n  order by time, channel\n"
    }
   ]
  },
  {
   "title": "net new docs (db/day)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "db IOQ Activity (type/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,\na.value-b.value as value from \n(SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  and host in ($host)\n  and ioqtype in ('db_compact','db_update')\n  group by ioqtype,mtime_epoch)a,\n  (SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and host in ($host)\n  and ioqtype in ('db_compact','db_update')\n  group by ioqtype,mtime_epoch)b\n  where a.metric=b.metric\n  and a.time-60 = b.time\n  order by time,value desc\n"
    }
   ]
  },
  {
   "title": "view pending updates (db total)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  sum(updates_pending_total) as value\nFROM\n  view_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and database in ($database) and view <> 'cfilter'\n  group by metric,time\n  order by time,metric"
    }
   ]
  },
  {
   "title": "view IOQ Activity (type/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,\na.value-b.value as value from \n(SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  and host in ($host)\n  and ioqtype in ('view_compact','view_update')\n  group by ioqtype,mtime_epoch)a,\n  (SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and host in ($host)\n  and ioqtype in ('view_compact','view_update')\n  group by ioqtype,mtime_epoch)b\n  where a.metric=b.metric\n  and a.time-60 = b.time\n  order by time,a.metric\n"
    }
   ]
  },
  {
   "title": "total docs (by db)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  database as metric,\n  mtime_epoch as time,\n  doc_count as value\nFROM\n  db_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and database in ($database)\n  order by time,metric\n"
    }
   ]
  },
  {
   "title": "doc inserts  (dbnode/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,\na.value-b.value as value from \n(SELECT\n  host as metric,\n  mtime_epoch as time,\n  sum(doc_inserts) as value\nFROM\n  host_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  and host in ($host)\n  group by host,mtime_epoch)a,\n  (SELECT\n  host as metric,\n  mtime_epoch as time,\n  sum(doc_inserts) as value\nFROM\n  host_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and host in ($host)\n  group by host,mtime_epoch)b\n  where a.metric=b.metric\n  and a.time-60 = b.time\n  order by time,a.metric\n"
    }
   ]
  },
  {
   "title": "doc updates (incl deletes)  (dbnode/min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,\na.value-b.value as value from \n(SELECT\n  host as metric,\n  mtime_epoch as time,\n  sum(doc_writes)-sum(doc_inserts) as value\n FROM\n  host_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  and host in ($host)\n  group by host,mtime_epoch)a,\n  (SELECT\n  host as metric,\n  mtime_epoch as time,\n  sum(doc_writes)-sum(doc_inserts) as value\nFROM\n  host_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster and host in ($host)\n  group by host,mtime_epoch)b\n  where a.metric=b.metric\n  and a.time-60 = b.time\n  order by time,metric"
    }
   ]
  },
  {
   "title": "ioq latency median (by dbnode) (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  host as metric,\n  mtime_epoch as time,\n  sum(ioql_med) as value\n FROM\n  host_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  and host in ($host)\n  group by host,mtime_epoch\n  order by time,metric\n"
    }
   ]
  }
 ]
}