{
 "title": "Endpoint Overview by Project",
 "description": "Endpoint Selectable Volumes and Response Times",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from endpoint_stats  group by cluster"
   },
   {
    "name": "project",
    "query": "SELECT CASE WHEN  substring(database,0,position('_' in database)) = '' THEN 'others' ELSE substring(database,0,position('_' in database)) END as project from endpoint_stats where cluster=$cluster and database is not null group by project order by project"
   },
   {
    "name": "database",
    "query": "select database from endpoint_stats where cluster=$cluster and CASE WHEN substring(database,0,position('_' in database)) = '' THEN 'others' ELSE substring(database,0,position('_' in database)) END in ($project) group by database order by database"
   },
   {
    "name": "endpoint",
    "query": "select endpoint from endpoint_stats where database in ($database) and cluster=$cluster group by endpoint order by endpoint"
   },
   { "name": "min_GET", "query": "SELECT 0,10,100,1000" },
   { "name": "min_POST", "query": "SELECT 0,10,100,1000" },
   { "name": "min_PUT", "query": "SELECT 0,10,100,1000" },
   { "name": "min_DELETE", "query": "select 0,10,100,1000" }
  ]
 },
 "panels": [
  {
   "title": "GET volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='GET' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(tqcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='GET' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(tqcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='PUT' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(tqcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='PUT' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE volume/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and tqcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='DELETE' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(tqcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='DELETE' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET travg (Cloudant db processing)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and trcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='GET' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database)  and verb='GET' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and trcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database)  and verb='POST' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and trcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database)  and verb='POST' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE  travg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and trcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='DELETE' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(trsum)/sum(trcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database)  and verb='DELETE' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET (tt-tr)avg (All except cloudant db)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and verb='GET' and database in ($database) and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='GET' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and verb='POST' and database in ($database) and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and verb='PUT' and database in ($database) and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='PUT' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE (tt-tr)avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and verb='DELETE' and database in ($database) and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,sum(ttrsum)/sum(ttrcount) as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster and database in ($database) and verb='DELETE' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "GET fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='GET' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster  and database in ($database) and verb='GET' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "POST fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='POST' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster  and database in ($database) and verb='POST' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "PUT fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='PUT' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster  and database in ($database) and verb='PUT' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  },
  {
   "title": "DELETE fail%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,\nc.time as time,\ncoalesce(d.value,0) as value from \n(select distinct a.database as metric,b.mtime_epoch as time from \n(select database from endpoint_stats where $__unixEpochFilter(mtime_epoch) and ttrcount >= cast($min_GET as int) and cluster=$cluster and database in ($database) and verb='DELETE' and endpoint in ($endpoint) group by database) a , \n(select mtime_epoch from endpoint_stats where $__unixEpochFilter(mtime_epoch) group by mtime_epoch) b \nwhere a.database in ($database))c \nLEFT OUTER JOIN \n(select database as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value from endpoint_stats\nwhere $__unixEpochFilter(mtime_epoch) and cluster=$cluster  and database in ($database) and verb='DELETE' and endpoint in ($endpoint)\ngroup by database,mtime_epoch)d \nON (c.metric = d.metric and c.time = d.time)\norder by time,metric"
    }
   ]
  }
 ]
}