{
 "title": "Traffic Explore Detail (Per Minute)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from body_endpoint_stats where  $__unixEpochFilter(mtime_epoch)  group by  chr(39)||cluster||chr(39)"
   },
   {
    "name": "projectphase",
    "query": "SELECT chr(39)||'%'||chr(39),chr(39)||'phr%'||chr(39),chr(39)||'koostekanta%'||chr(39),chr(39)||'kansa%'||chr(39)"
   },
   {
    "name": "database",
    "query": "select database from body_endpoint_stats where cluster = $cluster and client in ($client) and  database  like $projectphase  and $__unixEpochFilter(mtime_epoch) group by database  order by database"
   },
   {
    "name": "verb",
    "query": "select verb from body_endpoint_stats where cluster = $cluster and   $__unixEpochFilter(mtime_epoch) and client in ($client) and database in ($database) group by verb  order by verb"
   },
   {
    "name": "endpoint",
    "query": "select endpoint from body_endpoint_stats where cluster = $cluster   and client in ($client) and database  in ($database) and verb in ($verb)  and $__unixEpochFilter(mtime_epoch) group by endpoint  order by endpoint"
   },
   {
    "name": "exclude_endpoint",
    "query": "select 'None',endpoint from body_endpoint_stats where cluster = $cluster   and client in ($client) and database  in ($database) and verb in ($verb)  and $__unixEpochFilter(mtime_epoch) group by endpoint  order by endpoint"
   },
   {
    "name": "body",
    "query": "select body from body_endpoint_stats where cluster = $cluster and  database  in ($database) and verb in ($verb) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch) group by body  order by body"
   },
   {
    "name": "client",
    "query": "select client from body_endpoint_stats where cluster = $cluster and   $__unixEpochFilter(mtime_epoch) group by client order by client"
   },
   {
    "name": "exclude_client",
    "query": "select 'None',client from body_endpoint_stats where cluster = $cluster and   $__unixEpochFilter(mtime_epoch) group by client order by client"
   },
   {
    "name": "selectedtimes",
    "query": "SELECT substring(cast(mtime as varchar(12)) from 9 for 12) as minute from body_endpoint_stats where $__unixEpochFilter(mtime_epoch) group by 1 order by 1"
   },
   {
    "name": "measure",
    "query": "select chr(39)||measure||chr(39) from collector_stats group by measure order by measure"
   },
   { "name": "measure_type", "query": "SELECT 1,0" },
   {
    "name": "node",
    "query": "select node from collector_stats group by node order by node"
   },
   { "name": "offset", "query": "SELECT 7200,0" },
   {
    "name": "measure2",
    "query": "select chr(39)||measure||chr(39) from collector_stats group by measure order by measure"
   },
   { "name": "measure_type2", "query": "SELECT 1,0" }
  ]
 },
 "panels": [
  {
   "title": "$measure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.time as time,a.node as metric, \nCASE WHEN 1=$measure_type then a.value-b.value else a.value end as value from \n(select mtime_epoch+$offset as time,node,measure,value,counterseq from\ncollector_stats where  node in ($node) and measure = $measure and $__unixEpochFilter(mtime_epoch+$offset)) a\nJOIN\n(select mtime_epoch+$offset as time,node,measure,value,counterseq from \ncollector_stats where node in ($node) and measure = $measure and $__unixEpochFilter(mtime_epoch+$offset)) b\nON ((a.time= b.time + 10) or (a.time= b.time + 11)) and a.node=b.node and a.measure=b.measure\norder by time,metric"
    }
   ]
  },
  {
   "title": "$measure2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.time as time,a.node as metric, \nCASE WHEN 1=$measure_type2 then a.value-b.value else a.value end as value from \n(select mtime_epoch+$offset as time,node,measure,value,counterseq from\ncollector_stats where  node in ($node) and measure = $measure2 and $__unixEpochFilter(mtime_epoch+$offset)) a\nJOIN\n(select mtime_epoch+$offset as time,node,measure,value,counterseq from \ncollector_stats where node in ($node) and measure = $measure2 and $__unixEpochFilter(mtime_epoch+$offset)) b\nON ((a.time= b.time + 10) or (a.time= b.time + 11)) and a.node=b.node and a.measure=b.measure\norder by time,metric"
    }
   ]
  },
  {
   "title": "Counts",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,c.time as time, coalesce(d.value,0) as value from \n(select distinct b.time,a.metric from \n(SELECT endpoint as metric from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and verb in ($verb) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint ) a,\n(select mtime_epoch as time from body_endpoint_stats where cluster = $cluster  and database like $projectphase and client in ($client) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client)\ngroup by mtime_epoch) b)c \nLEFT OUTER JOIN \n(SELECT mtime_epoch as time,endpoint as metric,\nsum(ttcount) as value from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and verb in ($verb) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint,mtime_epoch )d\nON (c.metric=d.metric and c.time=d.time)\norder by time,metric\n"
    }
   ]
  },
  {
   "title": "tqavg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,c.time as time, coalesce(d.value,0) as value from \n(select distinct b.time,a.metric, b.all as all from \n(SELECT endpoint as metric from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint ) a,\n(select mtime_epoch as time ,sum(ttsum) as all from body_endpoint_stats where cluster = $cluster  and database like $projectphase and client in ($client) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client)\ngroup by mtime_epoch) b)c \nLEFT OUTER JOIN \n(SELECT mtime_epoch as time,endpoint as metric,\nsum(tqsum)/sum(tqcount) as value from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and verb in ($verb) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint,mtime_epoch )d\nON (c.metric=d.metric and c.time=d.time)\norder by time,metric\n"
    }
   ]
  },
  {
   "title": "travg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select c.metric as metric,c.time as time, coalesce(d.value,0) as value from \n(select distinct b.time,a.metric, b.all as all from \n(SELECT endpoint as metric from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint ) a,\n(select mtime_epoch as time ,sum(ttsum) as all from body_endpoint_stats where cluster = $cluster  and database like $projectphase and client in ($client) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client)\ngroup by mtime_epoch) b)c \nLEFT OUTER JOIN \n(SELECT mtime_epoch as time,endpoint as metric,\nsum(trsum)/sum(trcount) as value from body_endpoint_stats\nwhere cluster = $cluster  and database like $projectphase and client in ($client) and verb in ($verb) and endpoint in ($endpoint) and $__unixEpochFilter(mtime_epoch)\nand endpoint not in ($exclude_endpoint) and client not in ($exclude_client) group by endpoint,mtime_epoch )d\nON (c.metric=d.metric and c.time=d.time)\norder by time,metric\n"
    }
   ]
  },
  {
   "title": "Body-level Details (for $selectedtimes)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT client,database,verb,endpoint,body,substring(cast(mtime as varchar(12)) from 0 for 9) as day,\nsubstring(cast(mtime as varchar(12)) from 9 for 12) as minute,\ntrcount as count,tqmin,tqavg,tqmax,tqsum,trmin,travg,trmax,trsum,ttmin,ttavg,ttmax,ttsum,szmin,szavg,szmax from body_endpoint_stats\nwhere cluster = $cluster  and database in ($database) and $__unixEpochFilter(mtime_epoch)\nand substring(cast(mtime as varchar(12)) from 9 for 12) in ($selectedtimes) \nand verb in ($verb) and database in ($database)\nand endpoint in ($endpoint) and endpoint not in ($exclude_endpoint) and client in ($client) and client not in ($exclude_client)\nand body in ($body)\n\n"
    }
   ]
  }
 ]
}