{
 "title": "Volume Overview by Database",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from db_stats group by cluster"
   },
   { "name": "topn", "query": "select 10,20,50,100" },
   {
    "name": "min_db_size",
    "query": "select 0,1,10,100,500,1000,2000,5000"
   },
   {
    "name": "min_view_size",
    "query": "select 0,0.5,1,5,10,50,100,500,1000,5000,10000"
   },
   {
    "name": "db_report_datetime",
    "query": "select max(mtime) from db_stats where cluster=$cluster"
   },
   {
    "name": "view_report_datetime",
    "query": "select max(mtime) from view_stats where cluster=$cluster"
   }
  ]
 },
 "panels": [
  {
   "title": "Top $topn DBs by Disk Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,disk_size,now() as time  from (select database,rank() over (order by disk_size desc) as rnk,disk_size\nfrom db_stats where cluster = $cluster and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size ) a where rnk <=$topn \nUNION select 'others',11,coalesce(sum(disk_size),0),now() as time from (select database,rank() over (order by disk_size desc) as rnk,disk_size \nfrom db_stats where cluster = $cluster and  mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size ) a where rnk >$topn;\n\n"
    }
   ]
  },
  {
   "title": "Top $topn  DBs by View Disk Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,disk_size,now() as time  from (select database,rank() over (order by sum(disk_size) desc) as rnk,sum(disk_size) as disk_size\nfrom view_stats where cluster = $cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk <=$topn \nUNION select 'others',$topn+1,coalesce(sum(disk_size),0),now() as time from (select database,rank() over (order by sum(disk_size) desc) as rnk,sum(disk_size) as disk_size \nfrom view_stats  where cluster = $cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk >$topn;\n\n"
    }
   ]
  },
  {
   "title": "Top $topn  DBs by DocCount",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,doc_count,now() as time  from (select database,rank() over (order by doc_count desc) as rnk,doc_count\nfrom db_stats where cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size) a where rnk <=$topn \nUNION select 'others',$topn+1,coalesce(sum(doc_count),0),now() as time from (select database,rank() over (order by doc_count desc) as rnk,doc_count \nfrom db_stats where cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size) a  where rnk >$topn;\n"
    }
   ]
  },
  {
   "title": "Top $topn DBs by Compactable Database Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,compactable,now() as time  from (select database,rank() over (order by(disk_size-data_size) desc) as rnk,(disk_size-data_size) as compactable\nfrom db_stats where cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size ) a where rnk <=$topn \nUNION select 'others',11,coalesce(sum(compactable),0),now() as time from (select database,rank() over (order by (disk_size-data_size) desc) as rnk,(disk_size-data_size) as compactable \nfrom db_stats where  cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from db_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_db_size ) a where rnk >$topn;"
    }
   ]
  },
  {
   "title": "Top $topn DBs by Compactable View Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,compactable,now() as time  from (select database,rank() over (order by sum(disk_size-data_size) desc) as rnk,\nsum(disk_size-data_size) as compactable\nfrom view_stats where cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk <=$topn\nUNION select 'others',$topn+1,coalesce(sum(compactable),0),now() as time from (select database,rank() over (order by sum(disk_size-data_size) desc) as rnk,\nsum(disk_size-data_size) as compactable\nfrom view_stats where cluster=$cluster and  mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk >$topn;"
    }
   ]
  },
  {
   "title": "Top $topn DBs by Num of Views",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select database,rnk,viewcount,now() as time  from (select database,rank() over (order by count(disk_size) desc) as rnk,\ncount(disk_size) as viewcount\nfrom view_stats where cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk <=$topn\nUNION select 'others',$topn+1,coalesce(sum(viewcount),0),now() as time from (select database,rank() over (order by count(disk_size) desc) as rnk,\ncount(disk_size) as viewcount\nfrom view_stats where cluster=$cluster and  mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_view_size group by database) a where rnk >$topn;"
    }
   ]
  }
 ]
}