{
 "title": "Volume Overview by Cluster",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from db_stats group by cluster"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic All Clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select verb as metric,mtime_epoch as time,sum(tqcount) as value from client_verb_stats\nwhere $__unixEpochFilter(mtime_epoch)  and cluster=$cluster\ngroup by verb,mtime_epoch\norder by time,metric"
    }
   ]
  },
  {
   "title": "Document Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,value from \n((SELECT  'docs' as metric,  mtime_epoch as time,  sum(doc_count) as value\nFROM  db_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric) UNION \n(SELECT  'deleted' as metric,  mtime_epoch as time,  sum(del_doc_count) as value\nFROM  db_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric)) a\norder by time,metric"
    }
   ]
  },
  {
   "title": "Database Disk Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,value from \n((SELECT  'usage' as metric,  mtime_epoch as time,  sum(cast (disk_size/1048576 as decimal(8,2))) as value\nFROM  db_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric) UNION \n(SELECT  'compactable' as metric,  mtime_epoch as time,  sum(cast ((disk_size-data_size)/1048576 as decimal(8,2))) as value\nFROM  db_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric)) a\norder by time,metric\n\n"
    }
   ]
  },
  {
   "title": "Traffic - Filtered Clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select verb as metric,mtime_epoch as time,sum(tqcount) as value from verb_stats\nwhere $__unixEpochFilter(mtime_epoch)  and cluster=$cluster\ngroup by verb,mtime_epoch\norder by time,metric"
    }
   ]
  },
  {
   "title": "DB and View Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,value from \n((SELECT  'dbs' as metric,  mtime_epoch as time,  count(database) as value\nFROM  db_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric) UNION \n(SELECT  'views' as metric,  mtime_epoch as time,  count(view) as value\nFROM  view_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric)) a\norder by time,metric"
    }
   ]
  },
  {
   "title": "View Disk Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,value from \n((SELECT  'usage' as metric,  mtime_epoch as time,  sum(cast (disk_size/1048576 as decimal(8,2))) as value\nFROM  view_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by time order by time,metric) UNION \n(SELECT  'compactable' as metric,  mtime_epoch as time,  sum(cast ((disk_size-data_size)/1048576 as decimal(8,2))) as value\nFROM  view_stats WHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster  group by time order by time,metric)) a\norder by time,metric"
    }
   ]
  },
  {
   "title": "Avg Cloudant Processing (ms) - Filtered Clients",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select verb as metric,mtime_epoch as time,sum(tqsum/tqcount) as value from verb_stats\nwhere $__unixEpochFilter(mtime_epoch)  and cluster=$cluster\ngroup by verb,mtime_epoch\norder by time,metric"
    }
   ]
  },
  {
   "title": "ioq activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a.metric,a.time,\nCASE WHEN (a.value-b.value < 0) THEN 0 ELSE (a.value-b.value) END as value from \n(SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster  \n  group by ioqtype,mtime_epoch)a,\n  (SELECT\n  ioqtype as metric,\n  mtime_epoch as time,\n  sum(requests) as value\nFROM\n  ioq_stats\nWHERE\n  $__unixEpochFilter(mtime_epoch)\n  and cluster=$cluster \n  group by ioqtype,mtime_epoch)b\n  where a.metric=b.metric\n  and a.time-60 = b.time\n  order by time,value desc\n\n"
    }
   ]
  },
  {
   "title": "ioq Processing (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   'median' as metric,  mtime_epoch as time,  sum(ioql_med) as value FROM  host_stats\nWHERE  $__unixEpochFilter(mtime_epoch)  and cluster=$cluster   group by mtime_epoch   order by time,metric\n\n"
    }
   ]
  },
  {
   "title": "Traffic Fail Rate - Filtered Clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select verb as metric,mtime_epoch as time,\nCASE WHEN sum(st2count+st3count+st4count+st5count) = 0 then sum(0) else 100*sum(st3count+st4count+st5count)/sum(st2count+st3count+st4count+st5count) end as value \nfrom verb_stats\nwhere $__unixEpochFilter(mtime_epoch)  and cluster=$cluster\ngroup by verb,mtime_epoch\norder by time,metric"
    }
   ]
  }
 ]
}