{
 "title": "Volume Overview by View",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select chr(39)||cluster||chr(39) from db_stats group by cluster"
   },
   { "name": "topn", "query": "select 10,20,50,100" },
   {
    "name": "min_disk_size",
    "query": "select 0,0.1,0.2,0.5,1,2,5,10,20,50,100,200,500"
   },
   {
    "name": "view_report_datetime",
    "query": "select max(mtime) from view_stats where cluster=$cluster"
   }
  ]
 },
 "panels": [
  {
   "title": "Top $topn  Views by View Disk Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select view,rnk,disk_size,now() as time  from (select database||'/'||view as view,rank() over (order by sum(disk_size) desc) as rnk,sum(disk_size) as disk_size\nfrom view_stats where view <> 'cfilter'  and cluster = $cluster and mtime_epoch in (select max(mtime_epoch) from view_stats  where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk <=$topn \nUNION select 'others',$topn+1,coalesce(sum(disk_size),0),now() as time from (select database||'/'||view as view,rank() over (order by sum(disk_size) desc) as rnk,sum(disk_size) as disk_size \nfrom view_stats  where view <> 'cfilter'  and cluster = $cluster and mtime_epoch in (select max(mtime_epoch) from view_stats  where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk >$topn;\n\n"
    }
   ]
  },
  {
   "title": "Top $topn  Views  by UpdatesPending",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select view,rnk,updates_pending_total,now() as time  from (select database||'/'||view as view,rank() over (order by sum(updates_pending_total) desc) as rnk,sum(updates_pending_total) as updates_pending_total\nfrom view_stats where view<>'cfilter' and cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk <=$topn \nUNION select 'others',$topn+1,coalesce(sum(updates_pending_total),0),now() as time from (select database||'/'||view,rank() over (order by sum(updates_pending_total) desc) as rnk,sum(updates_pending_total)  as updates_pending_total\nfrom view_stats where view<>'cfilter' and cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk >$topn;\n"
    }
   ]
  },
  {
   "title": "Top $topn Views by Compactable View Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select view,rnk,compactable,now() as time  from (select database||'/'||view as view,rank() over (order by sum(disk_size-data_size) desc) as rnk,\nsum(disk_size-data_size) as compactable\nfrom view_stats where view<>'cfilter' and cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats  where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk <=$topn\nUNION select 'others',$topn+1,coalesce(sum(compactable),0),now() as time from (select database||'/'||view as view,rank() over (order by sum(disk_size-data_size) desc) as rnk,\nsum(disk_size-data_size) as compactable\nfrom view_stats where view<>'cfilter' and cluster=$cluster and  mtime_epoch in (select max(mtime_epoch) from view_stats  where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size group by database||'/'||view) a where rnk >$topn;"
    }
   ]
  },
  {
   "title": "Top $topn Views  by Compactable%",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select view,rnk,compactable,now() as time  from (select database||'/'||view as view,rank() over (order by 100*(disk_size-data_size)/disk_size desc) as rnk,\n100*(disk_size-data_size)/disk_size as compactable\nfrom view_stats where view<>'cfilter' and cluster=$cluster and mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster ) and disk_size::float/1048576  >= $min_disk_size) a where rnk <=$topn\nUNION select 'others',$topn+1,coalesce(100*sum(compactable)/sum(disk_size),0) as compactable,now() as time from (select database||'/'||view as view,rank() over (order by 100*(disk_size-data_size)/disk_size desc) as rnk,\n(disk_size-data_size) as compactable, disk_size as disk_size\nfrom view_stats where view<>'cfilter' and cluster=$cluster and  mtime_epoch in (select max(mtime_epoch) from view_stats where cluster=$cluster) and disk_size::float/1048576  >= $min_disk_size) a where rnk >$topn;"
    }
   ]
  }
 ]
}